spring:
  profiles:
    active: local
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        globally_quoted_identifiers: true
    defer-datasource-initialization: true
    database: mysql
  devtools:
    restart:
      enabled: false

server:
  port : 8082

logging:
  level:
    org:
      springframework:
        security=DEBUG:


